package dev.nucleusframework.desktop.application.internal.analyzer.detectors

import dev.nucleusframework.desktop.application.internal.analyzer.MethodSignature
import dev.nucleusframework.desktop.application.internal.analyzer.ReflectionEntry
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Framework-agnostic detector for project classes that are only reachable by reflection.
 *
 * Classes generated by annotation processors into the app's own module (Room `*_Impl`,
 * Dagger/Hilt `*_Factory`, Moshi adapters, …) never appear as constant-pool use-sites.
 * [ClassForNameDetector] cannot recover them when the library builds the name by
 * concatenation (`qualifiedName + "_Impl"`). Native-image then eliminates them.
 *
 * Invariant: a class in the **project's own output** that no bytecode on the classpath
 * references is, by construction, only reachable reflectively.
 *
 * Guards (keep cost bounded):
 * - Emit a nominative public no-arg `<init>` only — never `allDeclaredMethods` / fields.
 * - Concrete public classes with a public no-arg constructor only (drops Kotlin file facades).
 * - Supertype (class or interface, excluding bare `java.lang.Object`) must be referenced by
 *   **app** code — the shape of generated code (`AppDatabase_Impl extends AppDatabase`).
 *
 * Restricted to project class directories: dependency JARs explode with ServiceLoader-only
 * implementations already covered by L1/L2.
 *
 * @see <a href="https://github.com/NucleusFramework/Nucleus/issues/441">#441</a>
 */
internal object OrphanProjectClassDetector {
    private val NO_ARG_INIT = MethodSignature(name = "<init>", parameterTypes = emptyList())

    /**
     * One-pass header inspection of a project class file.
     * Returns null when the class file cannot be parsed.
     */
    fun inspect(classBytes: ByteArray): ProjectClassFact? {
        var access = 0
        var internalName = ""
        var superName: String? = null
        var interfaces: List<String> = emptyList()
        var hasPublicNoArgCtor = false
        try {
            ClassReader(classBytes).accept(
                object : ClassVisitor(Opcodes.ASM9) {
                    override fun visit(
                        version: Int,
                        accessFlags: Int,
                        name: String,
                        signature: String?,
                        superN: String?,
                        ifaces: Array<out String>?,
                    ) {
                        access = accessFlags
                        internalName = name
                        superName = superN?.replace('/', '.')
                        interfaces = ifaces?.map { it.replace('/', '.') }.orEmpty()
                    }

                    override fun visitMethod(
                        methodAccess: Int,
                        name: String?,
                        descriptor: String?,
                        signature: String?,
                        exceptions: Array<out String>?,
                    ): MethodVisitor? {
                        if (name == "<init>" &&
                            descriptor == "()V" &&
                            methodAccess and Opcodes.ACC_PUBLIC != 0
                        ) {
                            hasPublicNoArgCtor = true
                        }
                        return null
                    }
                },
                ClassReader.SKIP_CODE or ClassReader.SKIP_DEBUG or ClassReader.SKIP_FRAMES,
            )
        } catch (_: IllegalArgumentException) {
            return null
        }
        if (internalName.isEmpty()) return null

        val concretePublicNoArg =
            access and Opcodes.ACC_INTERFACE == 0 &&
                access and Opcodes.ACC_ABSTRACT == 0 &&
                access and Opcodes.ACC_ANNOTATION == 0 &&
                access and Opcodes.ACC_MODULE == 0 &&
                access and Opcodes.ACC_SYNTHETIC == 0 &&
                access and Opcodes.ACC_PUBLIC != 0 &&
                hasPublicNoArgCtor

        return ProjectClassFact(
            type = internalName.replace('/', '.'),
            concretePublicNoArg = concretePublicNoArg,
            superName = superName,
            interfaces = interfaces,
        )
    }

    /**
     * @param projectFacts facts for the project's own compiled classes only
     * @param classpathReferencedTypes FQCNs referenced by any class on the full runtime
     *   classpath (excluding self-references)
     * @param appReferencedTypes FQCNs referenced by project class files only
     */
    fun detect(
        projectFacts: Collection<ProjectClassFact>,
        classpathReferencedTypes: Set<String>,
        appReferencedTypes: Set<String>,
    ): Set<ReflectionEntry> {
        if (projectFacts.isEmpty()) return emptySet()
        val entries = mutableSetOf<ReflectionEntry>()
        for (fact in projectFacts) {
            if (fact.type in classpathReferencedTypes) continue
            if (!fact.concretePublicNoArg) continue
            if (!supertypeReferencedByApp(fact, appReferencedTypes)) continue
            entries.add(ReflectionEntry(type = fact.type, methods = setOf(NO_ARG_INIT)))
        }
        return entries
    }

    /**
     * Blanket registration of every project class that has a public no-arg constructor.
     * Opt-in sledgehammer (`graalvm { reflectionForProjectClasses = true }`).
     */
    fun detectAll(projectFacts: Collection<ProjectClassFact>): Set<ReflectionEntry> {
        if (projectFacts.isEmpty()) return emptySet()
        return projectFacts
            .filter { it.concretePublicNoArg }
            .map { ReflectionEntry(type = it.type, methods = setOf(NO_ARG_INIT)) }
            .toSet()
    }

    private fun supertypeReferencedByApp(
        fact: ProjectClassFact,
        appReferencedTypes: Set<String>,
    ): Boolean {
        val superName = fact.superName
        if (superName != null &&
            superName != "java.lang.Object" &&
            superName in appReferencedTypes
        ) {
            return true
        }
        return fact.interfaces.any { it in appReferencedTypes }
    }
}

/**
 * Compact header facts for one project class — produced once per class during the
 * single classpath walk, then consumed by [OrphanProjectClassDetector].
 */
internal data class ProjectClassFact(
    val type: String,
    val concretePublicNoArg: Boolean,
    val superName: String?,
    val interfaces: List<String>,
)
