package dev.nucleusframework.desktop.application.internal.analyzer.detectors

import dev.nucleusframework.desktop.application.internal.analyzer.MethodSignature
import dev.nucleusframework.desktop.application.internal.analyzer.ReflectionEntry

/**
 * Framework-agnostic detector for project classes that are only reachable by reflection.
 *
 * Classes generated by annotation processors into the app's own module (Room `*_Impl`,
 * Dagger/Hilt `*_Factory`, Moshi adapters, …) never appear as constant-pool references.
 * [ClassForNameDetector] cannot recover them either when the library builds the name by
 * concatenation (`qualifiedName + "_Impl"`). Native-image then eliminates them.
 *
 * Invariant: a class in the **project's own output** that no bytecode on the classpath
 * references is, by construction, only reachable reflectively.
 *
 * Guards (keep cost bounded):
 * - Emit a nominative public no-arg `<init>` only — never `allDeclaredMethods` / fields.
 * - Concrete public classes with a public no-arg constructor only (drops Kotlin file facades).
 * - Supertype (class or interface, excluding bare `java.lang.Object`) must be referenced by
 *   **app** code — the shape of generated code (`AppDatabase_Impl extends AppDatabase`).
 *
 * Restricted to project class directories: dependency JARs explode with ServiceLoader-only
 * implementations already covered by L1/L2.
 *
 * @see <a href="https://github.com/NucleusFramework/Nucleus/issues/441">#441</a>
 */
internal object OrphanProjectClassDetector {
    private val NO_ARG_INIT = MethodSignature(name = "<init>", parameterTypes = emptyList())

    /**
     * @param projectClassBytes map of internal class name (`com/foo/Bar`) → class bytes for
     *   the project's own compiled output only
     * @param classpathReferencedTypes FQCNs referenced by any class on the full runtime
     *   classpath (excluding self-references). A project class present in this set is not orphaned.
     * @param appReferencedTypes FQCNs referenced by project class files only (for the
     *   supertype-is-used-by-app guard)
     */
    fun detect(
        projectClassBytes: Map<String, ByteArray>,
        classpathReferencedTypes: Set<String>,
        appReferencedTypes: Set<String>,
    ): Set<ReflectionEntry> {
        if (projectClassBytes.isEmpty()) return emptySet()

        val entries = mutableSetOf<ReflectionEntry>()
        for ((internalName, bytes) in projectClassBytes) {
            val fqcn = internalName.replace('/', '.')
            if (fqcn in classpathReferencedTypes) continue

            if (!ClassReferenceCollector.isConcreteWithPublicNoArgCtor(bytes)) continue

            val supertypes = ClassReferenceCollector.collectSupertypes(bytes)
            if (!supertypeReferencedByApp(supertypes, appReferencedTypes)) continue

            entries.add(
                ReflectionEntry(
                    type = fqcn,
                    methods = setOf(NO_ARG_INIT),
                ),
            )
        }
        return entries
    }

    /**
     * Blanket registration of every project class that has a public no-arg constructor.
     * Opt-in sledgehammer (`graalvm { reflectionForProjectClasses = true }`) — measurable
     * image growth, never a default.
     */
    fun detectAllProjectClasses(projectClassBytes: Map<String, ByteArray>): Set<ReflectionEntry> {
        if (projectClassBytes.isEmpty()) return emptySet()
        val entries = mutableSetOf<ReflectionEntry>()
        for ((internalName, bytes) in projectClassBytes) {
            if (!ClassReferenceCollector.isConcreteWithPublicNoArgCtor(bytes)) continue
            entries.add(
                ReflectionEntry(
                    type = internalName.replace('/', '.'),
                    methods = setOf(NO_ARG_INIT),
                ),
            )
        }
        return entries
    }

    /**
     * Supertype must be something the app actually uses — not bare `Object` (always
     * "referenced") and not an unused hierarchy leaf.
     */
    private fun supertypeReferencedByApp(
        supertypes: ClassReferenceCollector.Supertypes,
        appReferencedTypes: Set<String>,
    ): Boolean {
        val superName = supertypes.superName
        if (superName != null &&
            superName != "java.lang.Object" &&
            superName in appReferencedTypes
        ) {
            return true
        }
        return supertypes.interfaces.any { it in appReferencedTypes }
    }
}
