/*
 * Copyright 2020-2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

package dev.nucleusframework.desktop.application.internal

import org.gradle.api.GradleException
import java.io.File

/**
 * Stages the user's PKG install scripts where electron-builder's PKG target picks them up.
 *
 * electron-builder resolves `pkg.scripts` against its build-resources directory (`<project>/build`)
 * and hands the directory to `pkgbuild --scripts`, which runs the files named exactly `preinstall`
 * and `postinstall` as the package's top-level scripts.
 *
 * **It also declares them a second time.** For every file whose name contains `preinstall` /
 * `postinstall`, electron-builder sets `BundlePreInstallScriptPath` / `BundlePostInstallScriptPath`
 * in the component property list, so the generated `PackageInfo` carries both a bundle-level and a
 * top-level entry and macOS Installer runs each script **twice** — verified on a real install. To
 * spare every app that papercut, the staged `preinstall` / `postinstall` are small shims: the app's
 * own script is staged under a name electron-builder does not scan for, and the shim runs it once,
 * on the top-level pass.
 */
internal object MacPkgScripts {
    /** Directory name under electron-builder's build resources, and the value written to `pkg.scripts`. */
    const val SCRIPTS_DIR = "pkg-scripts"

    private const val PRE_INSTALL = "preinstall"
    private const val POST_INSTALL = "postinstall"

    /**
     * Names the app's own scripts are staged under. They must not contain the substrings
     * `preinstall` / `postinstall`, or electron-builder would point the bundle-level entry at them
     * and the deduplication below would be bypassed.
     */
    private fun userScriptName(topLevelName: String) =
        when (topLevelName) {
            PRE_INSTALL -> "nucleus-app-pre"
            else -> "nucleus-app-post"
        }

    /**
     * Runs the app's script exactly once.
     *
     * Installer passes the install location as `$2` to a top-level script and the installed bundle
     * path to a bundle-level one, so the pass to skip is the one whose `$2` is the `.app` itself.
     */
    private fun shim(userScript: String) =
        """
        #!/bin/sh
        # Generated by Nucleus. electron-builder declares this script twice in PackageInfo (once per
        # bundle, once top level), so macOS Installer would run the app's script twice. The per-bundle
        # pass receives the installed bundle as ${'$'}2 — skip it and run on the top-level pass only.
        case "${'$'}2" in
            *.app|*.app/) exit 0 ;;
        esac
        exec "${'$'}(dirname "${'$'}0")/$userScript" "${'$'}@"
        """.trimIndent() + "\n"

    /**
     * Copies [preInstall] / [postInstall] into `<buildResourcesDir>/pkg-scripts`, each behind a
     * deduplicating shim, exec bit set. The directory is always wiped first so a script from a
     * previous run cannot leak into a build that no longer declares it. Returns the staged
     * directory, `null` when no script is configured.
     *
     * Fails when a script is declared for an App Store PKG (Apple rejects packages with install
     * scripts, validation error 90254), when a declared file is missing, or when it has no shebang
     * (Installer executes the file directly).
     */
    fun stage(
        buildResourcesDir: File,
        preInstall: File?,
        postInstall: File?,
        appStore: Boolean,
    ): File? {
        val scriptsDir = buildResourcesDir.resolve(SCRIPTS_DIR)
        scriptsDir.deleteRecursively()

        val scripts =
            listOfNotNull(
                preInstall?.let { PRE_INSTALL to it },
                postInstall?.let { POST_INSTALL to it },
            )
        if (scripts.isEmpty()) return null
        if (appStore) {
            fail(
                "macOS { pkg { preInstall / postInstall } } requires pkg { appStore = false }: " +
                    "the Mac App Store rejects installer packages that carry install scripts (error 90254).",
            )
        }

        scriptsDir.mkdirs()
        for ((topLevelName, source) in scripts) {
            validateScript(topLevelName, source)

            val userScriptName = userScriptName(topLevelName)
            val userScript = scriptsDir.resolve(userScriptName)
            source.copyTo(userScript, overwrite = true)
            userScript.setExecutable(true, false)

            val entryPoint = scriptsDir.resolve(topLevelName)
            entryPoint.writeText(shim(userScriptName))
            entryPoint.setExecutable(true, false)
        }
        return scriptsDir
    }

    private fun validateScript(
        name: String,
        source: File,
    ) {
        if (!source.isFile) fail("PKG $name script not found: ${source.absolutePath}")
        if (!source.readText().startsWith("#!")) {
            fail(
                "PKG $name script must start with a shebang (e.g. #!/bin/sh), " +
                    "the Installer executes it directly: ${source.absolutePath}",
            )
        }
    }

    private fun fail(message: String): Nothing = throw GradleException(message)
}
