package dev.nucleusframework.desktop.application.internal

import java.io.File
import java.util.zip.ZipFile

/**
 * Keep rules for the providers JARs declare in `META-INF/services`, generated for the ProGuard pass.
 *
 * Nothing references a provider but its service file, so ProGuard drops or renames it and
 * `ServiceLoader` finds nothing: JDBC drivers, the SLF4J binding, Lucene codecs, Ktor's default
 * engine, JLine's terminal providers. R8 keeps them on its own; ProGuard has no notion of it.
 * Names are validated as Java binary names before they reach a rule, so a service file cannot
 * inject options.
 */
internal object ServiceProviderRules {
    const val DIRECTORY = "META-INF/services/"

    /** Compile-time SPIs: an annotation processor is never loaded by the application it ships in. */
    private val COMPILE_TIME_SERVICES = setOf("javax.annotation.processing.Processor")
    private val BINARY_NAME = Regex("""[\p{L}_$][\p{L}\p{N}_$]*(\.[\p{L}_$][\p{L}\p{N}_$]*)*""")

    /** Whether the application loads [service] at run time. */
    fun isRuntimeService(service: String): Boolean = service !in COMPILE_TIME_SERVICES

    /** The first of [service] and [providers] that is not a Java binary name, if any. */
    fun invalidName(
        service: String,
        providers: List<String>,
    ): String? = (listOf(service) + providers).firstOrNull { !it.matches(BINARY_NAME) }

    /** Provider class names of a `META-INF/services` file: one per line, `#` comments. */
    fun providers(content: String): List<String> =
        content
            .lineSequence()
            .map { it.substringBefore('#').trim() }
            .filter { it.isNotEmpty() }
            .distinct()
            .toList()

    /**
     * Keeps every provider of [providers] (service binary name → provider binary names) under its
     * own name with the constructor `ServiceLoader` calls. A service the application ships
     * ([programClasses]) keeps its name too, and its providers only when the service itself
     * survives shrinking, as R8 does; a JDK service (`java.sql.Driver`) keeps them always.
     */
    fun rules(
        providers: Map<String, Set<String>>,
        programClasses: Set<String>,
    ): String =
        buildString {
            appendLine("# Generated by Nucleus from the META-INF/services files of the input JARs.")
            for ((service, impls) in providers) {
                val shipped = service in programClasses
                if (shipped) appendLine("-keepnames class $service")
                for (impl in impls) {
                    if (shipped) appendLine("-if class $service")
                    appendLine("-keep class $impl { public <init>(); public static ** provider(); }")
                }
            }
        }

    /** Binary names of every class in [jars]. */
    fun programClasses(jars: List<File>): Set<String> =
        jars
            .filter { it.isFile }
            .flatMap { jar ->
                runCatching {
                    ZipFile(jar).use { zip ->
                        zip
                            .entries()
                            .asSequence()
                            .map { it.name }
                            .filter { it.endsWith(".class") && !it.startsWith("META-INF/") }
                            .map { it.removeSuffix(".class").replace('/', '.') }
                            .toList()
                    }
                }.getOrDefault(emptyList())
            }.toSet()
}
